### ISSUE TITLE
Retriever ckpt on MSMARCO

### ISSUE THREAD

**Issue by caiyinqiong** [microsoft/AR2#7]
Hi, congrats for the great work! 
Can you release the retriever ckpt after AR2 training on MSMARCO? 

Thank you.

**Comment by hangzhang-nlp** [comment]
https://msraprophetnet.blob.core.windows.net/ar2/realease_ckpt/marco_finetinue.pkl

**Comment by hangzhang-nlp** [comment]
https://msraprophetnet.blob.core.windows.net/ar2/realease_ckpt/marco_finetune.pkl

**Comment by caiyinqiong** [comment]
Great. Thank you~
